java -Xms1024M -Xmx1024M -Djava.library.path=natives/ -cp ^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/github/ImpactDevelopment/SimpleTweaker/1.2/SimpleTweaker-1.2.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/5kws/baritone-api/1.6.3/baritone-api-1.6.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/httpcomponets/httpcore/4.3.2/httpcore-4.3.2.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;^
C:\Users\jmc18\AppData\Roaming/.minecraft/versions/1.16.5/1.16.5.jar ^
net.minecraft.launchwrapper.Launch --username ledreth@gmail.com --version 1.16.5-Baritone --gameDir C:\Users\jmc18\AppData\Roaming/.minecraft --assetsDir C:\Users\jmc18\AppData\Roaming/.minecraft/assets --assetIndex 1.16 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZDdiNTVmZTE0ZjQ0YTk5OTkyZDUxZWE3Y2ExYjQ2NyIsInlnZ3QiOiJlM2FiOWEzMmU0NjU0MjIyYmY3NWM0N2RkNWQ5YTZmMCIsInNwciI6ImVhM2E5NDBjZTJlZTQyMWU4MGFjZjNkOWFhOGY4Njk3IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MTMxOTMwNDMsImlhdCI6MTYxMzAyMDI0M30.17HvC0NS8x_o-7HpadGguKBTfxMCTQcZeoTD4qW2SRg --userType mojang --tweakClass baritone.launch.BaritoneTweaker
